stages:
  data_collection:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/train_model.py
    deps:
    - data/processed
    - src/model/train_model.py
    outs:
    - logistic_regression_model.pkl
  model_eval:
    cmd: python src/model/model_eval.py
    deps:
    - logistic_regression_model.pkl
    - src/model/model_eval.py
    metrics:
    - metrics.json
